import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { RESTAURANTS } from '../public/scripts/restaurants.js';
import { brandIcon, tableArt, restaurantArt } from './artwork.mjs';

const publicDir = fileURLToPath(new URL('../public/', import.meta.url));
const esc = (s) => String(s).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#39;');
const route = (r) => `/restaurants/${r.id}`;
const directions = (r) => `https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${r.name}, Washington, DC`)}&travelmode=walking`;
const nav = (active) => `<header class="site-header"><div class="container header-inner"><a class="brand" href="/" aria-label="The Twifords Try D.C., home">${brandIcon}<span>The Twifords<br> Try D.C.</span></a><nav class="site-nav" aria-label="Main navigation">${[['/', 'Restaurants'], ['/map', 'Map'], ['/about', 'About the gift'], ['/gift-cards', 'Gift cards']].map(([href, text]) => `<a href="${href}"${text === active ? ' aria-current="page"' : ''}${text === 'Gift cards' ? ' class="nav-card"' : ''}>${text}</a>`).join('')}</nav></div></header>`;
const footer = `<footer class="site-footer"><div class="container footer-inner"><p>For Jack &amp; Anne. With love, Rae Rae &amp; Darragh.</p><form action="/api/logout" method="post"><button class="text-button" type="submit">Sign out</button></form></div></footer>`;
const shell = (title, active, body, extra = '') => `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} | The Twifords Try D.C.</title><meta name="robots" content="noindex"><meta name="description" content="Four D.C. restaurants and a gift card for each, picked for Jack and Anne by Rae Rae and Darragh."><meta name="theme-color" content="#b81d34"><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 48 48'%3E%3Ccircle cx='24' cy='24' r='22' fill='%23b81d34'/%3E%3Ctext x='24' y='33' text-anchor='middle' font-family='Georgia' font-size='30' fill='white'%3ET%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="/styles/organic.css"><link rel="stylesheet" href="/styles/site.css"><script type="module" src="/scripts/site.js"></script>${extra}</head><body><a class="skip-link" href="#main">Skip to content</a>${nav(active)}<main id="main">${body}</main>${footer}</body></html>\n`;
const cards = RESTAURANTS.map((r) => `<article class="restaurant-card"><a class="restaurant-link" href="${route(r)}"><div class="card-art ${r.color}">${restaurantArt(r.id)}</div><div class="card-meta"><span>${esc(r.neighborhood)}</span><span aria-hidden="true">/</span><span>${esc(r.cuisine)}</span></div><h3>${esc(r.name)}</h3><p>${esc(r.description)}</p><div class="card-footer"><span>$${r.giftCard.amount} gift card included</span><span>Take a look</span></div></a></article>`).join('');
const pages = {
  'index.html': shell('Restaurants', 'Restaurants', `<div class="container"><section class="hero"><div class="hero-copy"><span class="hero-context">A wedding gift for Jack &amp; Anne</span><h1>A few dinners<br>in your<br>new city.</h1><p>Four D.C. restaurants we think you’ll love, with a gift card for each. Pick a place and make a night of it.</p><div class="actions"><a class="btn btn-primary" href="/gift-cards">Find your gift cards</a><a class="btn btn-secondary" href="/map">See the map</a></div></div><figure class="hero-art">${tableArt}<figcaption>Washington, D.C.</figcaption></figure></section><section class="guide-section" aria-labelledby="restaurants-heading"><div class="section-heading"><h2 id="restaurants-heading">Where to go</h2><p>Four places, picked by Rae Rae &amp; Darragh</p></div><div class="restaurant-grid">${cards}</div></section><section class="home-note"><h2>Try these before<br>we come to visit.</h2><div><p>We’re so happy for you both. Here are a few recommendations to help you get to know D.C. You can show us around next time.</p><a href="/about">About the gift</a></div></section></div>`),
  'gift-cards.html': shell('Gift cards', 'Gift cards', `<div class="container"><header class="page-intro"><h1>Your gift cards.</h1><p>A $30 card for each restaurant. Open a card for the details you’ll need when you pay.</p></header><div class="wallet-grid">${RESTAURANTS.map((r) => `<a class="wallet-card ${r.color}" href="${route(r)}#gift-card"><div class="wallet-top"><div><h2>${esc(r.name)}</h2><p>${esc(r.giftCard.label)}</p></div><strong>$${r.giftCard.amount}</strong></div><div class="wallet-bottom"><span>For Jack &amp; Anne</span><b>Open gift card</b></div></a>`).join('')}</div><p class="wallet-help">Amounts shown are the original gift values, not live balances. Use the provider’s balance link where available, or ask the restaurant. Keep your card details private.</p></div>`),
  'map.html': shell('Map', 'Map', `<div class="container"><header class="page-intro"><h1>Find your next dinner.</h1><p>Four spots across D.C. Select a restaurant to find it on the map, or open its page for your gift card.</p></header><div class="map-layout"><div class="map-list">${RESTAURANTS.map((r, i) => `<article class="map-entry" data-restaurant-index="${i}"><div class="map-entry-head"><span class="map-number">${i + 1}</span><h2>${esc(r.name)}</h2></div><p>${esc(r.neighborhood)} / ${esc(r.cuisine)}</p><div class="map-entry-actions"><button type="button" data-focus="${i}" hidden>Show on map</button><a href="${route(r)}">Restaurant &amp; card</a></div></article>`).join('')}</div><div class="map-frame"><iframe id="dcmap" src="/dc-map" title="Map of the four restaurants in Washington, D.C."></iframe></div></div></div>`),
  'about.html': shell('About the gift', 'About the gift', `<div class="container welcome-page"><h1>Welcome to DC.</h1></div>`),
};
for (const r of RESTAURANTS) {
  pages[`restaurants/${r.id}.html`] = shell(r.name, 'Restaurants', `<div class="container"><header class="page-intro"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Restaurants</a><span aria-hidden="true">/</span><span aria-current="page">${esc(r.name)}</span></nav><h1>${esc(r.name)}</h1><p>${esc(r.description)}</p></header><div class="detail-grid"><section class="detail-copy" aria-label="About ${esc(r.name)}"><div class="detail-art ${r.color}">${restaurantArt(r.id)}</div><div class="detail-meta"><span class="tag">${esc(r.neighborhood)}</span><span class="tag">${esc(r.cuisine)}</span></div><div class="actions"><a class="btn btn-primary" href="${esc(r.web)}" target="_blank" rel="noopener noreferrer">Restaurant website <span aria-hidden="true">↗</span></a><a class="btn btn-secondary" href="${directions(r)}" target="_blank" rel="noopener noreferrer">Get directions <span aria-hidden="true">↗</span></a></div><p class="gift-hint">Check the restaurant’s website for hours, menus, and reservations.</p></section><section class="voucher" id="gift-card" data-card-id="${r.id}" aria-labelledby="gift-title"><div class="voucher-top"><div class="voucher-topline"><h2 id="gift-title">Your gift card</h2><span class="voucher-amount">$${r.giftCard.amount}</span></div><p>${esc(r.giftCard.label)}</p></div><div class="voucher-body"><p class="voucher-recipient">For Jack &amp; Anne Twiford</p><div id="card-details" class="card-status" aria-live="polite"><p>Loading your gift card…</p><noscript><p>Enable JavaScript to securely load your private gift card details.</p></noscript></div>${r.giftCard.note ? `<p class="gift-note">${esc(r.giftCard.note)}</p>` : ''}<p class="gift-fine">Original gift value: $${r.giftCard.amount}. The provider’s terms apply. This page does not track your remaining balance.</p></div></section></div><section class="more-restaurants"><h2>Also on your list</h2><div class="more-links">${RESTAURANTS.filter((other) => other.id !== r.id).map((other) => `<a href="${route(other)}">${esc(other.name)}</a>`).join('')}</div></section></div>`);
}
export async function buildPages() {
  await mkdir(`${publicDir}/restaurants`, { recursive: true });
  await Promise.all(Object.entries(pages).map(([file, html]) => writeFile(`${publicDir}/${file}`, html)));
}
await buildPages();
console.log(`Built ${Object.keys(pages).length} static pages.`);
